### Step 1) Register or create new user
POST http://microbloglite.us-east-2.elasticbeanstalk.com/api/users
Content-Type: application/json

{
    "username": "Adethapiper1",
    "fullName": "Adeyemi Adepoju",
    "password": "Ade123"
}


### Step 2) Login
POST http://microbloglite.us-east-2.elasticbeanstalk.com/auth/login
Content-Type: application/json

{
  "username": "Adethapiper1",
  "password": "Ade123"
}

### Step 3) GET Users
GET http://microbloglite.us-east-2.elasticbeanstalk.com/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNocmlzIiwiaWF0IjoxNzE5NDIxMjU5LCJleHAiOjE3MTk1MDc2NTl9.AmfECplxBMt46Rtu8YDkpZ-Hf8eqVpWpxB5gmhyziEM
### Step 4) GET One User

GET http://microbloglite.us-east-2.elasticbeanstalk.com/api/Chris
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNocmlzIiwiaWF0IjoxNzE5NDIxMjU5LCJleHAiOjE3MTk1MDc2NTl9.AmfECplxBMt46Rtu8YDkpZ-Hf8eqVpWpxB5gmhyziEM

### Step 5) Create a Post
POST http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNocmlzIiwiaWF0IjoxNzE5NDIxMjU5LCJleHAiOjE3MTk1MDc2NTl9.AmfECplxBMt46Rtu8YDkpZ-Hf8eqVpWpxB5gmhyziEM

{
    "text": "yup"
}

### Step 6) GET Posts
GET http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNocmlzIiwiaWF0IjoxNzE5NDIxMjU5LCJleHAiOjE3MTk1MDc2NTl9.AmfECplxBMt46Rtu8YDkpZ-Hf8eqVpWpxB5gmhyziEM

### Step 7) DELETE Post
DELETE http://microbloglite.us-east-2.elasticbeanstalk.com/api
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNocmlzIiwiaWF0IjoxNzE5NDIxMjU5LCJleHAiOjE3MTk1MDc2NTl9.AmfECplxBMt46Rtu8YDkpZ-Hf8eqVpWpxB5gmhyziEM


### Step 8) Update User
PUT http://microbloglite.us-east-2.elasticbeanstalk.com/api/users/Chris
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNocmlzIiwiaWF0IjoxNzE5NDIxMjU5LCJleHAiOjE3MTk1MDc2NTl9.AmfECplxBMt46Rtu8YDkpZ-Hf8eqVpWpxB5gmhyziEM

{
"fullName" : "Adeyemi Adepoju",
"bio": "Hi"
}
### Step 9) Add Like
POST http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts/6675a240fbf13c2cc0eaf724/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNocmlzIiwiaWF0IjoxNzE5NDIxMjU5LCJleHAiOjE3MTk1MDc2NTl9.AmfECplxBMt46Rtu8YDkpZ-Hf8eqVpWpxB5gmhyziEM

### Step 10) Delete/Remove Like
DELETE http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts/6675a240fbf13c2cc0eaf724/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNocmlzIiwiaWF0IjoxNzE5NDIxMjU5LCJleHAiOjE3MTk1MDc2NTl9.AmfECplxBMt46Rtu8YDkpZ-Hf8eqVpWpxB5gmhyziEM